### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by jasonwynn10** [jasonwynn10/AirSneakBoots#1]
- [x] Add License
- [x] Add plugin files
- [x] Implement Poggit Builds
- [ ] Test Boots
- [ ] Debug errors
- [ ] Create Poggit Release
